# Global theme definitions
[themes]
[light]
h1 = "text-4xl font-bold text-gray-900"
h2 = "text-3xl font-bold text-gray-800"
h3 = "text-2xl font-semibold text-gray-700"
span = "font-medium text-gray-600"
link = "text-blue-600 hover:text-blue-800 underline"
input = "border border-gray-300 rounded-md px-3 py-2 focus:ring-2 focus:ring-blue-500"
img = "object-cover"
time = "text-sm text-gray-500"

[dark]
h1 = "text-4xl font-bold text-white"
h2 = "text-3xl font-bold text-gray-100"
h3 = "text-2xl font-semibold text-gray-200"
span = "font-medium text-gray-300"
link = "text-blue-400 hover:text-blue-300 underline"
input = "border border-gray-600 bg-gray-800 text-white rounded-md px-3 py-2"
img = "object-cover"
time = "text-sm text-gray-400"
