# schemas/users/users.toml

# Field variants - how each field can be rendered
[variants.name]
h1 = { base = "h1", override = "text-2xl font-bold" }
h2 = { base = "h2", override = "text-xl font-semibold" }
display = { base = "h1", override = "text-2xl font-bold text-center" }

[variants.email]
link = { base = "a", attrs = { href = "mailto:{value}" } }
input = { base = "input", attrs = { type = "email", value = "{value}" } }

[variants.avatar_url]
large = { base = "img", override = "w-12 h-12 rounded-full", attrs = { alt = "{name}", src = "{value}" } }
small = { base = "img", override = "w-8 h-8 rounded-full", attrs = { alt = "{name}", src = "{value}" } }

[variants.created_at]
time = { base = "time" }
full = { base = "span", override = "text-sm text-gray-500" }

# Default variants for each field
[defaults]
name = "h1"
email = "link"
avatar_url = "small"
created_at = "time"

# Contexts - which variant to use in different UI situations
[contexts.card]
name = "h2"
email = "link"
avatar_url = "large"
created_at = "time"

[contexts.list]
inherits = "card"
avatar_url = "small"
created_at = "full"

# Mock data for testing and development
[[mock_data]]
id = "1"
name = "John Doe"
email = "john@example.com"
avatar_url = "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150"
created_at = "2024-01-15T10:30:00Z"

[[mock_data]]
id = "2"
name = "Jane Smith"
email = "jane.smith@example.com"
avatar_url = "https://images.unsplash.com/photo-1494790108755-2616b612b786?w=150"
created_at = "2024-01-14T09:15:00Z"

[[mock_data]]
id = "3"
name = "Bob Wilson"
email = "bob@company.com"
avatar_url = "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150"
created_at = "2024-01-13T14:22:00Z"
